#ifndef __GN_OVERSEA_CUSTOM_USB_NAME_H__
#define __GN_OVERSEA_CUSTOM_USB_NAME_H__
#define GN_USB_MANUFACTURER_STRING "GIONEE"
#define GN_USB_PRODUCT_STRING "E7"
#define GN_USB_VENDOR_ID_8C GIONEE
#define GN_USB_DISK_ID_16C E7
#define GN_USB_CDROM_ID_16C E7
#endif
